[tool.isort]
profile     = "black"
line_length = 100

[tool.black]
quiet          = true
line-length    = 100
target-version = ['py39']

[tool.pylint.messages_control]
disable = "no-self-argument, redefined-builtin"
extension-pkg-allow-list = "pydantic"
