[tool.black]
quiet          = true
line-length    = 100
target-version = ['py39']

[tool.pylint.messages_control]
disable = "no-self-argument, redefined-builtin"
extension-pkg-allow-list = "pydantic"

[tool.ruff]
fix = true
select = [
            "F", "B", "Q", "W", "C90", "I", "UP", "N", "YTT", "BLE", "A", "C4",
            "ICN", "RET", "SIM", "ARG", "PL", "COM", "DTZ", "EM", "EXE", "ISC",
            "G", "PIE", "PYI", "PT", "RSE", "SLF", "TCH", "PTH", "RUF"
         ]
