[tool.black]
quiet          = true
line-length    = 100
target-version = ['py39']

[tool.pylint.messages_control]
disable = "no-self-argument, redefined-builtin"
extension-pkg-allow-list = "pydantic"

[tool.ruff]
fix = true
select = [
            "E", "F", "B", "Q", "W", "C90", "I", "D", "UP", "N", "YTT", "BLE",
            "FBT", "A", "C4", "ICN", "RET", "SIM", "ARG", "PLC", "PLE", "PLR",
            "PLW"
         ]
